version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PHP_VERSION: ${DOCKER_SRC_PHP_VERSION}
    container_name: ${DOCKER_PREFIX}_${DOCKER_CNAME_PHP}
    restart: unless-stopped
    working_dir: /var/www
    environment:
      - DB_USERNAME=${MYSQL_USER}
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./src:/var/www
      - ./docker/app/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - internal
  server:
    image: nginx:${DOCKER_SRC_NGINX_VERSION}
    container_name: ${DOCKER_PREFIX}_${DOCKER_CNAME_SERVER}
    restart: unless-stopped
    volumes:
      - ./src:/var/www
      - ./docker/server/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    networks:
      - internal
  db:
    image: mariadb:${DOCKER_SRC_MARIADB_VERSION}
    container_name: ${DOCKER_PREFIX}_${DOCKER_CNAME_DB}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3307:3306" # allow local MySQL to run freely
    volumes:
      - db:/var/lib/mysql
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  db: